name: clip
description: .
version: 1.2.0
homepage: https://github.com/hsul4n/dart-clip

environment:
  sdk: ">2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  photo_view: ^0.13.0
  image_picker: ^0.8.4+4
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  test: ^1.5.1
